spring:
  application:
    name: Product

  jpa:
    show-sql: true
    hibernate:
        ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/dbTest?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

logging:
  level:
    br.com.gx2.product: info


