spring:
  application:
    name: Product

  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    br.com.example.product: info


